<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="AddSchedule.aspx.cs" Inherits="OnlineHobby.AddSchedule" MasterPageFile="~/StudMaster.Master" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">

    <style type="text/css">
        .cssInputTr {
            width: 200px;
            padding: 5px;
            text-align: left;
            border-right: 1px solid grey;
        }

        .cssTitleTr {
            width: 200px;
            text-align: right;
        }

        table {
            border-bottom: 1px solid grey;
            border-top: 1px solid grey;
            border-left: 1px solid grey;
            border-right: 1px solid grey;
        }

        .div-background {
            background-color: #fffefa;
        }
    </style>

    <div style="padding: 20px; font-size: 20px; margin-left: 5%; margin-right: 5%; text-align: center" class="auto-style1">

        <table style="width: 100%; border-">
            <tr>
                <td class="cssTitleTr">Start Date :</td>
                <td class="cssInputTr">
                    <div class="input-group bootstrap-datepicker datepicker">
                        <asp:TextBox ID="txtStartDate" runat="server" Width="180px" CssClass="form-control" TextMode="Date" Font-Size="20px"></asp:TextBox>
                        <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                    </div>
                </td>
                <td rowspan="5" align="center">
                    <h4>Schedule for the course</h4>
                    <asp:GridView ID="gvCourseSchedule" runat="server" AutoGenerateColumns="False" DataKeyNames="scheduleId" EmptyDataText="There are no data records to display." Height="220px" Width="95%" Font-Size="20px" OnSelectedIndexChanged="gvCourseSchedule_SelectedIndexChanged" class="table table-bordered table-condensed table-hover" AutoGenerateSelectButton="True" AutoGenerateDeleteButton="True" OnRowDeleting="gvCourseSchedule_RowDeleting">
                        <Columns>
                            <asp:BoundField DataField="scheduleId" HeaderText="ID" ReadOnly="True" SortExpression="scheduleId" />
                            <asp:BoundField DataField="tutoringMode" HeaderText="Tutoring Mode" SortExpression="tutoringMode" />
                            <asp:BoundField DataField="meetingLink" HeaderText="Meeting Link" SortExpression="meetingLink" />
                            <asp:BoundField DataField="maxStud" HeaderText="Maximum Student" SortExpression="maxStud" />
                            <asp:BoundField DataField="price" HeaderText="Price" SortExpression="price" DataFormatString="{0:C}" />
                        </Columns>
                        <EditRowStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                    </asp:GridView>
                </td>
            </tr>
            <tr>
                <td class="cssTitleTr">&nbsp;</td>
                <td class="cssInputTr">&nbsp;</td>
            </tr>
            <tr>
                <td class="cssTitleTr">Time Begin :</td>
                <td class="cssInputTr">

                    <asp:TextBox ID="txtTime" CssClass="form-control" Width="180px" runat="server" TextMode="Time" Font-Size="20px"></asp:TextBox>

                </td>
            </tr>
            <tr>
                <td class="cssTitleTr">&nbsp;</td>
                <td class="cssInputTr">&nbsp;</td>
            </tr>
            <tr>
                <td class="cssTitleTr">Tutoring Mode :</td>
                <td class="cssInputTr">
                    <asp:DropDownList ID="ddlTutoringMode" runat="server" Width="180px" Font-Size="20px" AutoPostBack="True" OnSelectedIndexChanged="ddlTutoringMode_SelectedIndexChanged">
                        <asp:ListItem Value="oneToMany">One to Many</asp:ListItem>
                        <asp:ListItem Value="oneToOne">One to One</asp:ListItem>
                    </asp:DropDownList>
                </td>
            </tr>
            <tr>
                <td class="cssTitleTr">&nbsp;</td>
                <td class="cssInputTr">&nbsp;</td>
                <td rowspan="6" align="center">
                    <h4>Schedule List</h4>
                    <asp:GridView ID="gvScheduleList" runat="server" class="table table-bordered table-condensed table-hover" Width="90%" AutoGenerateColumns="False" DataKeyNames="scheduleListId" EmptyDataText="There are no data records to display." Font-Size="20px">
                        <Columns>
                            <asp:BoundField DataField="date" HeaderText="Date" SortExpression="date" ReadOnly="True" DataFormatString="{0:dd/MM/yyyy}" />
                            <asp:BoundField DataField="time" HeaderText="Time" SortExpression="time" ReadOnly="True" />
                        </Columns>
                        <EditRowStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                    </asp:GridView>
                </td>
            </tr>
            <tr>
                <td class="cssTitleTr">Maximum Student :</td>
                <td class="cssInputTr">
                    <asp:TextBox ID="txtMaxStud" runat="server" Width="180px" CssClass="form-control" Font-Size="20px"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td class="cssTitleTr">&nbsp;</td>
                <td class="cssInputTr">&nbsp;</td>
            </tr>
            <tr>
                <td class="cssTitleTr">Meeting Link :</td>
                <td class="cssInputTr">
                    <asp:TextBox ID="txtMeetLink" runat="server" Width="180px" CssClass="form-control" Font-Size="20px"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td class="cssTitleTr">&nbsp;</td>
                <td class="cssInputTr">&nbsp;</td>
            </tr>
            <tr>
                <td class="cssTitleTr">Price for Course :</td>
                <td class="cssInputTr">
                    <asp:TextBox ID="txtPrice" runat="server" Width="180px" CssClass="form-control" Font-Size="20px"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td class="cssInputTr">
                    <asp:Button ID="btnAddSchedule" runat="server" Text="ADD" CssClass="button btn-lg rounded-pill" Style="height: 47px; width: 150px; margin: 10px; background-color: #f98006; color: white; border-color: transparent" OnClick="btnAddSchedule_Click" />
                </td>
                <td>&nbsp;</td>
            </tr>
        </table>
        <br />
        <br />
        <asp:Button ID="btnNext" runat="server" Text="Next" OnClick="btnNext_Click" CssClass="btn btn-light btn-lg rounded-pill" Style="height: 47px; width: 165px; background-color: #f98006; color: white" />
    </div>
</asp:Content>
